[package]
name = "trees"
description = "git worktrees simplified"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
git2 = "0.20.2"
iocraft = "0.7.10"
smol = "2.0.2"
